### ISSUE TITLE
Add extra metadata types property and itemprop

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#109]
At this moment, it is impossible to generate Facebook Open Graph metadata or Google+ metadata, because we need to generate the following meta tags : 

```
<!-- Schema.org markup for Google+ -->
<meta itemprop="name" content="ImpressCMS">

<!-- Open Graph data -->
<meta property="og:locale" content="<{$icms_langcode}>" />

```
For that, we'll need to add the metadata types property and itemprop

**Comment by MekDrop** [comment]
I think this is related to SEO functionality and because SEO needs always changes maybe would be a better idea to use integrated library like https://github.com/ARCANEDEV/SEO-Helper But from other side i'm not sure if that doesn't requires much more work and that's why maybe the way how you are solving this is better for now... I don't see there anything bad but i'm not sure how much can be this useful for us in the future :/
