### ISSUE TITLE
Force HTTPS option

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#171]
Some browsers asks users to use https only on some domains. We need setting in cms settings to redirect user if he come from http domain.

https://stackoverflow.com/questions/85816/how-can-i-force-users-to-access-my-page-over-https-instead-of-http

**Comment by fiammybe** [comment]
As far as I have done until now, that is a setting in the apache config. FOr those that don't have access to the apache config, that can be useful.

However, we must be vigilant to keep the number of 'forwards' as low as possible. I think this should be one of the steps in the routing process, but we should be bundling a maximum of alterations to the destination address as possible. So not go from http to https, only to then look if the current page needs to be rerouted to something else (like the login page).

**Comment by skenow** [comment]
Is this something we really want to do? It requires the admin to have https available and setup, or the redirect fails, or we have to perform extra tests, or both. And, as David points out, we can add a lot of misdirects if the target page does not exist, even in http. I really believe this is a server config, rather than a cms config.

**Comment by MekDrop** [comment]
I think we can leave this as is. Probably if somebody needs such functionality module could be developed later for that.
