### ISSUE TITLE
Should ICMS use Smarty?

### ISSUE THREAD

**Issue by MekDrop** [ImpressCMS/impresscms#238]
Should we upgrade to [Smaty 3](https://www.smarty.net/docs/en/) or we should use different template engine?

Our options:
* [Dwoo](http://dwoo.org/)- has [smarty compatibility](http://dwoo.org/plugins/processors/smarty-compat.html) layer and is written in object style.
* [Twig](https://twig.symfony.com) - used by Symfony and many others. Similar to smarty but has some differences
* [Blade](https://laravel.com/docs/5.6/blade) - like Twig is similar but it's possible to use PHP code directly in templates

**Comment by fiammybe** [comment]
Let’s first go for Smarty 2 split off from the code, but using an external library, then we could look into smarty3 or Dwoo.

Twig is using a big part of symfony, which would make ImpressCMS much bigger. I would limit dependencies for the moment.

**Comment by MekDrop** [comment]
Than question is there any reason why we can't use smarty 3? From what I see here everything should work after upgrade -> https://raw.githubusercontent.com/smarty-php/smarty/master/SMARTY_2_BC_NOTES.txt

**Comment by fiammybe** [comment]
No reason, I tried 2 years ago to do an upgrade by simply replacing the libraries, but because of the way Smarty is currently weaved into the core I only was able to obtain a blank page :-) That is why I would expect it to be easier once smarty2 would be included in the vendor map via composer.

**Comment by MekDrop** [comment]
I think you have missed something and that the upgrade doesn't worked.

**Comment by fiammybe** [comment]
things have evolved a bit since the ticket started. Dwoo is no longer active, so I wouldn't recommend going for that. 
Steve mentioned correctly on slack a few weeks ago that we should keep in mind that the old sites should be able to do an upgrade from 1.4 -> 2.0. If we change the fundamental templating system, I don't think that will be possible.
Personally, I don't think remaining in Smarty is a good thing, not for the long haul. It is no longer being improved, so I don't think there will ever be a v4.

Mustache (https://github.com/bobthecow/mustache.php) might be an option as well, it looks easy and simple to use (and that is not necessarily a bad thing). It even offers caching if you want, but let's face it, Twig and Blade are the ones coming out on top these days.

**Comment by MekDrop** [comment]
Yeah, you right.

There is Smarty 3 pull request already.

Mustache as main templating system probably wouldn't fit for us. Is good for renering markdowns or some other simple documents but problems starts when you need to do something more.

**Comment by fiammybe** [comment]
Yes, I'll have a look at PR #249 later. 
It was the simplicity of Mustache that appealed to me, but you are right that we sometimes do complex things in our templates. Perhaps that is not a good thing, but for the moment it is that way.

**Comment by fiammybe** [comment]
As promised I had a look at #249 , much later than expected because i needed a stable internet connection to perform composer install. 1 but in the admin page as far as I can see.
