### ISSUE TITLE
Local caching gravatar files

### ISSUE THREAD

**Issue by fiammybe** [ImpressCMS/impresscms#317]
The gravatar files are retrieved every time. Investigate the possibility of caching the gravatar files on the impresscms server.

**Comment by MekDrop** [comment]
maybe for build-in avatars some caching could make sense but I don't think that this would make sense with gravatars. All caching should be monitored with gravatar.com service because otherwise there is no triggers to know when user changed own avatar there. So, user can see old gravatar when new was uploaded.

**Comment by fiammybe** [comment]
Good point, this has no real sense. And loading from gravatar shouldn't slow down the loading of the pages either. Closing :-)
