### ISSUE TITLE
Phoenix migrations

### ISSUE THREAD

**Issue by lulco** [ImpressCMS/impresscms#630]
Hi, I am the author of phoenix migrations. I really appreciate you use it in your CMS.

 I would like to ask few questions:
- How did you get to phoenix?
- Why did you pick phoenix instead of some other migration tools (like phinx)?
- Did you find some issues / bugs / features needed in phoenix? Especially in dump command you probably used when creating initialization migration.

Thank you very much.

**Comment by MekDrop** [comment]
Thanks @lulco for your awesome work!

I can't remember where I found phoenix, but I think that was when I was searching packagist.org about migrations tools. I remember I tried with phinx first but I was a bit stuck how to easy make add migrations support to modules. And than I found about phoenix, that has already support for different paths. I tried and it worked!

So far so good. Only one possible issue I have found - different folders use same namespace when generating migrations. But because we still haven't released final ImpressCMS version with phoenix don't know is this really to think about it.

**Comment by lulco** [comment]
Thank you for your answer!

If you will find any bug, please create issue in phoenix repository and I will try to fix it and in case of feature I will consider if it would be usable for other users.

About namespaces: for now it is up to you which namespace you use for each migration. You can do this when creating migration two ways:

1) php vendor/bin/phoenix create "MyNamespace\MyFirstMigration" which creates migration with namespace
2) php vendor/bin/phoenix create MyFirstMigration which creates migration without namespace and you can add namespace to class manually (before executing it)

**Comment by MekDrop** [comment]
Thanks didn't know about that!

**Comment by lulco** [comment]
No problem, just ask and I will answer (if I will know the answer).
