### ISSUE TITLE
Unable to open block edit through edit icon - front end and admin area

### ISSUE THREAD

**Issue by skenow** [ImpressCMS/impresscms#918]
## Describe the bug
the edit dialog does not open when clicking the icon for the block

## To Reproduce
1. sign in with sufficient privileges to edit blocks
2. theme is iTheme
3. click on the icon for a block

## Expected behavior
dialog opens to select action for the block

## console message
Uncaught TypeError: $(...).dialog is not a function
    onclick http://localhost/test14/admin.php#:1

**Comment by skenow** [comment]
Replacing the version of jQuery that is delivered with 1.4 with the version from 1.3.11 resolves the issue.

**Comment by fiammybe** [comment]
the old jQuery has some significant security risks, so we'll have to update our javascript for the latest version.

**Comment by fiammybe** [comment]
When I look on Stackoverflow, this issue is linked several times with the fact that multiple jQuery versions were loaded : https://stackoverflow.com/questions/26016562/error-typeerror-dialog-is-not-a-function 

I remember there is a place where ImpressCMS will automatically load several js libraries, that could be a place to improve (it was not configurable).

**Comment by skenow** [comment]
This may be related to #925 - properly including the jQuery scripts now results in being able to open the edit dialog on the front end.

Will you test and confirm, @fiammybe ?

**Comment by fiammybe** [comment]
this is now working, after #935
